# Import Libraries

In [22]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.layers import Dense, Input, GlobalMaxPooling1D
from keras.layers import Conv1D, MaxPooling1D, Embedding
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.models import Model

# Loading Dataset

In [23]:
xls = pd.ExcelFile('Dataset.xlsx')
df1 = pd.read_excel(xls, 'final video data')
df2 = pd.read_excel(xls, 'final comment all')
df3 = pd.read_excel(xls, 'all 3 vid link')

In [24]:
df1.head()

,title,description,videoLength,thumbnailUrl,videoId,videoUrl,channelId,channelUrl,keywords,averageRating,...,likeCount,dislikeCount,authorThumbnailUrl,subscriberCount,category,publishDate,isLiveContent,isFamilySafe,query,timestamp
0,Heroes in the Cockpit! American Airlines fligh...,Get 70% off on the Two year deal with Nord VPN...,1502,https://i.ytimg.com/vi/Gv5EQlzM1B8/hqdefault.jpg,Gv5EQlzM1B8,https://www.youtube.com/watch?v=Gv5EQlzM1B8,UCwpHKudUkP5tNgmMdexB3ow,https://www.youtube.com/channel/UCwpHKudUkP5tN...,"american airlines flight 96, aa flight 96, Avi...",4.958981,...,9362,97,https://yt3.ggpht.com/ytc/AKedOLT9pb_6-sg0v0F4...,755K subscribers,People & Blogs,2021-03-19,False,1.0,https://www.youtube.com/watch?v=Gv5EQlzM1B8,2021-06-29T07:45:15.820Z
1,The Soldier Who Hated Nazis So Much He Joined ...,Joseph Beyrle was a young American soldier who...,551,https://i.ytimg.com/vi/juUOsZVsco8/maxresdefau...,juUOsZVsco8,https://www.youtube.com/watch?v=juUOsZVsco8,UCl3SuH2Ue044b7ACX1syk4A,https://www.youtube.com/channel/UCl3SuH2Ue044b...,NaN,4.938184,...,5670,89,https://yt3.ggpht.com/ytc/AKedOLSmPn6MvYu_AhvN...,716K subscribers,Education,2021-06-28,False,1.0,https://www.youtube.com/watch?v=juUOsZVsco8,2021-06-29T07:45:18.077Z
2,The Woman who Wore Pants and Won a Medal of Honor,"Out of 3,500 people who have been awarded the ...",588,https://i.ytimg.com/vi/6y6XzEajBNs/maxresdefau...,6y6XzEajBNs,https://www.youtube.com/watch?v=6y6XzEajBNs,UCl3SuH2Ue044b7ACX1syk4A,https://www.youtube.com/channel/UCl3SuH2Ue044b...,"history channel, civil war, history, documenta...",4.915872,...,4003,86,https://yt3.ggpht.com/ytc/AKedOLSmPn6MvYu_AhvN...,716K subscribers,Education,2021-06-24,False,1.0,https://www.youtube.com/watch?v=6y6XzEajBNs,2021-06-29T07:45:19.647Z
3,Operation Outward,Subscribe to Dark Docs: https://bitly.com/Dark...,588,https://i.ytimg.com/vi/WZuwbOtIx-w/maxresdefau...,WZuwbOtIx-w,https://www.youtube.com/watch?v=WZuwbOtIx-w,UCl3SuH2Ue044b7ACX1syk4A,https://www.youtube.com/channel/UCl3SuH2Ue044b...,"world war 2, operation outward, secret, classi...",4.946477,...,7226,98,https://yt3.ggpht.com/ytc/AKedOLSmPn6MvYu_AhvN...,716K subscribers,Education,2021-06-21,False,1.0,https://www.youtube.com/watch?v=WZuwbOtIx-w,2021-06-29T07:45:21.635Z
4,The Dentist who Dropped His Drill and Extracte...,Captain Benjamin Lewis Salomon was a US Army d...,508,https://i.ytimg.com/vi/J7Wsb2MP92A/maxresdefau...,J7Wsb2MP92A,https://www.youtube.com/watch?v=J7Wsb2MP92A,UCl3SuH2Ue044b7ACX1syk4A,https://www.youtube.com/channel/UCl3SuH2Ue044b...,"ww2, wwii, world war 2, world war ii, document...",4.961028,...,5895,58,https://yt3.ggpht.com/ytc/AKedOLSmPn6MvYu_AhvN...,716K subscribers,Education,2021-06-17,False,1.0,https://www.youtube.com/watch?v=J7Wsb2MP92A,2021-06-29T07:45:23.494Z

In [25]:
df2.head()

,video_url,comment_user,content,comment_time,like_count,dislike_count,reply_count,post_like_count,post_dislike_count,CrawlTime
0,https://www.youtube.com/watch?v=juUOsZVsco8,The ATF,This manâ€™s life story is just â€œwhat is every s...,1 day ago,185,NaN,4,8076,141,1630000000000
1,https://www.youtube.com/watch?v=juUOsZVsco8,Shane Khiu,When you change faction mid game but still com...,1 day ago,156,NaN,undefined,8076,141,1630000000000
2,https://www.youtube.com/watch?v=juUOsZVsco8,Obama dodecahedron,His plot armor is stronger than Reyâ€™s,1 day ago,356,NaN,18,8076,141,1630000000000
3,https://www.youtube.com/watch?v=juUOsZVsco8,Ross Christopher,The German guards: ITS ONLY BEEN 10 MINUTES HE...,1 day ago,83,NaN,2,8076,141,1630000000000
4,https://www.youtube.com/watch?v=juUOsZVsco8,logan holmberg,"Now, here's a story that deserves a movie or m...",1 day ago,338,NaN,18,8076,141,1630000000000

In [26]:
df3.head()

,videoUrl,videoTitle,thumbnailUrl,duration,viewCount,postDate,query,timestamp
0,https://www.youtube.com/watch?v=juUOsZVsco8,The Soldier Who Hated Nazis So Much He Joined ...,https://i.ytimg.com/vi/juUOsZVsco8/hqdefault.jpg,09:12:00,61000.0,10 hours ago,https://www.youtube.com/channel/UCl3SuH2Ue044b...,2021-06-29T03:37:24.865Z
1,https://www.youtube.com/watch?v=6y6XzEajBNs,The Woman who Wore Pants and Won a Medal of Honor,https://i.ytimg.com/vi/6y6XzEajBNs/hqdefault.jpg,09:49:00,53000.0,4 days ago,https://www.youtube.com/channel/UCl3SuH2Ue044b...,2021-06-29T03:37:24.865Z
2,https://www.youtube.com/watch?v=WZuwbOtIx-w,Operation Outward,https://i.ytimg.com/vi/WZuwbOtIx-w/hqdefault.jpg,09:48:00,154000.0,1 week ago,https://www.youtube.com/channel/UCl3SuH2Ue044b...,2021-06-29T03:37:24.865Z
3,https://www.youtube.com/watch?v=J7Wsb2MP92A,The Dentist who Dropped His Drill and Extracte...,https://i.ytimg.com/vi/J7Wsb2MP92A/hqdefault.jpg,08:28:00,101000.0,1 week ago,https://www.youtube.com/channel/UCl3SuH2Ue044b...,2021-06-29T03:37:24.865Z
4,https://www.youtube.com/watch?v=SL5rfU6JBsA,American Tank vs German Tank Caught on Camera ...,https://i.ytimg.com/vi/SL5rfU6JBsA/hqdefault.jpg,10:24:00,328000.0,2 weeks ago,https://www.youtube.com/channel/UCl3SuH2Ue044b...,2021-06-29T03:37:24.865Z

# Cleaning Dataset

In [27]:
cleaned_df2 = df2[['video_url','post_like_count', 'post_dislike_count']]
cleaned_df2=cleaned_df2.drop_duplicates(subset ="video_url")
cleaned_df2.columns = ['videoUrl', 'post_like_count', 'post_dislike_count']
cleaned_df2=cleaned_df2.reset_index(drop="True")
cleaned_df2.head()

,videoUrl,post_like_count,post_dislike_count
0,https://www.youtube.com/watch?v=juUOsZVsco8,8076,141
1,https://www.youtube.com/watch?v=WZuwbOtIx-w,7402,104
2,https://www.youtube.com/watch?v=6y6XzEajBNs,4052,89
3,https://www.youtube.com/watch?v=J7Wsb2MP92A,5931,58
4,https://www.youtube.com/watch?v=rFkEqbfeb7o,10824,108

In [28]:
cleaned_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763 entries, 0 to 762
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   videoUrl            763 non-null    object
 1   post_like_count     763 non-null    object
 2   post_dislike_count  763 non-null    int64
dtypes: int64(1), object(2)
memory usage: 18.0+ KB

In [29]:
cleaned_df3 = df3[['videoUrl','viewCount','duration','videoTitle']]
cleaned_df3=cleaned_df3.drop_duplicates(subset ="videoUrl")
cleaned_df3.head()

,videoUrl,viewCount,duration,videoTitle
0,https://www.youtube.com/watch?v=juUOsZVsco8,61000.0,09:12:00,The Soldier Who Hated Nazis So Much He Joined ...
1,https://www.youtube.com/watch?v=6y6XzEajBNs,53000.0,09:49:00,The Woman who Wore Pants and Won a Medal of Honor
2,https://www.youtube.com/watch?v=WZuwbOtIx-w,154000.0,09:48:00,Operation Outward
3,https://www.youtube.com/watch?v=J7Wsb2MP92A,101000.0,08:28:00,The Dentist who Dropped His Drill and Extracte...
4,https://www.youtube.com/watch?v=SL5rfU6JBsA,328000.0,10:24:00,American Tank vs German Tank Caught on Camera ...

In [30]:
cleaned_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 818 entries, 0 to 817
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   videoUrl    818 non-null    object
 1   viewCount   818 non-null    float64
 2   duration    818 non-null    object
 3   videoTitle  818 non-null    object
dtypes: float64(1), object(3)
memory usage: 32.0+ KB

In [31]:
cleaned_df1 = df1[['videoUrl','description']]
cleaned_df1=cleaned_df1.drop_duplicates(subset ="videoUrl")
cleaned_df1.head()

,videoUrl,description
0,https://www.youtube.com/watch?v=Gv5EQlzM1B8,Get 70% off on the Two year deal with Nord VPN...
1,https://www.youtube.com/watch?v=juUOsZVsco8,Joseph Beyrle was a young American soldier who...
2,https://www.youtube.com/watch?v=6y6XzEajBNs,"Out of 3,500 people who have been awarded the ..."
3,https://www.youtube.com/watch?v=WZuwbOtIx-w,Subscribe to Dark Docs: https://bitly.com/Dark...
4,https://www.youtube.com/watch?v=J7Wsb2MP92A,Captain Benjamin Lewis Salomon was a US Army d...

In [32]:
cleaned_df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 818
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   videoUrl     819 non-null    object
 1   description  819 non-null    object
dtypes: object(2)
memory usage: 19.2+ KB

In [33]:
dfs = [cleaned_df1, cleaned_df2, cleaned_df3]

In [34]:
from functools import reduce
cleaned_data = reduce(lambda left,right: pd.merge(left,right,on='videoUrl'), dfs)

In [35]:
cleaned_data.head()

,videoUrl,description,post_like_count,post_dislike_count,viewCount,duration,videoTitle
0,https://www.youtube.com/watch?v=juUOsZVsco8,Joseph Beyrle was a young American soldier who...,8076,141,61000.0,09:12:00,The Soldier Who Hated Nazis So Much He Joined ...
1,https://www.youtube.com/watch?v=6y6XzEajBNs,"Out of 3,500 people who have been awarded the ...",4052,89,53000.0,09:49:00,The Woman who Wore Pants and Won a Medal of Honor
2,https://www.youtube.com/watch?v=WZuwbOtIx-w,Subscribe to Dark Docs: https://bitly.com/Dark...,7402,104,154000.0,09:48:00,Operation Outward
3,https://www.youtube.com/watch?v=J7Wsb2MP92A,Captain Benjamin Lewis Salomon was a US Army d...,5931,58,101000.0,08:28:00,The Dentist who Dropped His Drill and Extracte...
4,https://www.youtube.com/watch?v=SL5rfU6JBsA,Get your SPECIAL OFFER for MagellanTV here: ht...,11551,400,328000.0,10:24:00,American Tank vs German Tank Caught on Camera ...

In [36]:
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 763 entries, 0 to 762
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   videoUrl            763 non-null    object
 1   description         763 non-null    object
 2   post_like_count     763 non-null    object
 3   post_dislike_count  763 non-null    int64
 4   viewCount           763 non-null    float64
 5   duration            763 non-null    object
 6   videoTitle          763 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 47.7+ KB

In [16]:


MAX_SEQUENCE_LENGTH = 1000
#MAX_NB_WORDS = 2000
MAX_NB_WORDS = 15000
VALIDATION_SPLIT = 0.2
EMBEDDING_DIM = 100

NUM_BINS = 5


np.random.seed(0)

def top_k_percentile_views_mask(df, k):
    top_k_percent = df['viewCount'].nlargest(int(df.shape[0] * (k / 100.))).iloc[-1]
    return df['viewCount'] > top_k_percent

embeddings_index = {}
f = open('glove.6B/glove.6B.{0}d.txt'.format(EMBEDDING_DIM), encoding='utf8')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print ('Found %s word vectors.' % len(embeddings_index))


print ('Now processing titles')

Using TensorFlow backend.

Found 400000 word vectors.
Now processing titles

In [37]:
cleaned_data['Percentile-Bin'] = pd.qcut(cleaned_data['viewCount'], NUM_BINS, labels=range(NUM_BINS))
cleaned_data = cleaned_data.dropna()
cleaned_data.head()

,videoUrl,description,post_like_count,post_dislike_count,viewCount,duration,videoTitle,Percentile-Bin
0,https://www.youtube.com/watch?v=juUOsZVsco8,Joseph Beyrle was a young American soldier who...,8076,141,61000.0,09:12:00,The Soldier Who Hated Nazis So Much He Joined ...,0
1,https://www.youtube.com/watch?v=6y6XzEajBNs,"Out of 3,500 people who have been awarded the ...",4052,89,53000.0,09:49:00,The Woman who Wore Pants and Won a Medal of Honor,0
2,https://www.youtube.com/watch?v=WZuwbOtIx-w,Subscribe to Dark Docs: https://bitly.com/Dark...,7402,104,154000.0,09:48:00,Operation Outward,0
3,https://www.youtube.com/watch?v=J7Wsb2MP92A,Captain Benjamin Lewis Salomon was a US Army d...,5931,58,101000.0,08:28:00,The Dentist who Dropped His Drill and Extracte...,0
4,https://www.youtube.com/watch?v=SL5rfU6JBsA,Get your SPECIAL OFFER for MagellanTV here: ht...,11551,400,328000.0,10:24:00,American Tank vs German Tank Caught on Camera ...,1

In [41]:
X = cleaned_data['title']
y = cleaned_data['Percentile-Bin']

In [ ]:

texts = set()
for x in X:
    texts.add(x)

tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

labels = to_categorical(np.asarray(y))
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)


indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]
nb_validation_samples = int(VALIDATION_SPLIT * data.shape[0])

x_train = data[:-nb_validation_samples]
y_train = labels[:-nb_validation_samples]
x_val = data[-nb_validation_samples:]
y_val = labels[-nb_validation_samples:]


num_words = min(MAX_NB_WORDS, len(word_index.items())) + 1
embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))
for word, i in word_index.items():
    if i >= MAX_NB_WORDS or i >= num_words:
        continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

embedding_layer = Embedding(num_words,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

print('Training model.')


sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = LSTM(128)(x)
x = Dense(128, activation='relu')(x)
preds = Dense(NUM_BINS, activation='softmax')(x)

model = Model(sequence_input, preds)
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

model.fit(x_train, y_train,
          batch_size=50,
          epochs=10,
          validation_data=(x_val, y_val))

scores = model.evaluate(x_val, y_val, verbose=0)

model.save('predictor.h5')

Found 13353 unique tokens.
Shape of data tensor: (763, 1000)
Shape of label tensor: (763, 5)
Training model.
Train on 611 samples, validate on 152 samples
Epoch 1/10
611/611 [==============================] - 10s 17ms/step - loss: 1.6815 - acc: 0.1817 - val_loss: 1.6438 - val_acc: 0.1776
Epoch 2/10
450/611 [=====================>........] - ETA: 2s - loss: 1.6215 - acc: 0.1889